language: python
python:
    - "3.5"
sudo: false
matrix:
    - python: 2.7
      env: TOX_ENV=py27
    - python: 3.5
      env: TOX_ENV=py35
    - python: 3.5
      env: TOX_ENV=flake8
    - python: 3.5
      env: TOX_ENV=docs
      # power job
    - python: 2.7
      env: TOX_ENV=py27
      arch: ppc64le
    - python: 3.5
      env: TOX_ENV=py35
      arch: ppc64le
    - python: 3.5
      env: TOX_ENV=flake8
      arch: ppc64le
    - python: 3.5
      env: TOX_ENV=docs 
      arch: ppc64le
addons:
    apt:
        packages:
            - libev-dev
            - libevent-dev
install:
  - python setup.py develop
  - pip install tox
script: tox
after_success:
  - pip install coveralls
  - coveralls
notifications:
    email: tarek@mozilla.com
    irc: "irc.freenode.org#mozilla-circus"
    on_success: change
